config/routes.rb
Rails.application.routes.draw do
  #get 'reviews/new'
  #get 'sessions/new'
  root 'static_pages#home'
  get '/login',     to: "sessions#new"
  post 'login',     to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :studios
  resources :users
  resources :favorites, only:[:create, :destroy]
  resources :reviews, only:[:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save {email.downcase! }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  #カラムの名前をmount_uploaderに指定
  #THUMBNAIL_SIZE = [100, 100]
  mount_uploader :image, ImageUploader
  #作ったスタジオ user.create_studiosで呼び出せる
  #(class_nameは子のクラス名を指定、foreign_keyは子が親を呼び出すための外部キーカラム名)
  has_many :create_studios, class_name: "Studio", foreign_key: 'created_user_id'
  #お気に入り 以下のhas_manyを逆にするとエラーになる
  has_many :favorites
  has_many :favorite_studios, through: :favorites, source: :studio
  #レビュー
  has_many :reviews, dependent: :destroy
  

  #トークンを生成するメソッド
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  #引数の文字列のダイジェストを返すメソッド
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #引数のトークンがremember_digestとあっているか？を認証するメソッド
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :log_in_user, only:[:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録に成功しました。"
      log_in @user
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "ユーザー登録に失敗しました。"
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @studios = @user.favorite_studios.includes(:hash_tags, :hash_tag_relationships, :reviews, :accesses, :weekday_fee).paginate(page: params[:page], per_page: 6)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    if user
      flash[:success] = "プロフィール情報を更新しました。"
      user.update_attributes(user_params)
      redirect_to user
    else
      flash.now[:danger] = "プロフィール情報を更新できませんでした。"
      render "edit"
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] =   "退会処理が完了しました。"
    redirect_to root_path
  end
  
  private
  
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :image
        )  
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    if current_user == user
      true
    else
      false
    end
  end
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_messages">
  <% @user.errors.full_messages.each do |message| %>
    <ul>
      <li class="error-messages"><%= message %></li>
    </ul>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "error_messages" %>
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label "ユーザー名(必須項目)" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "メールアドレス(必須項目)" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "パスワード(必須項目)" %>
    <%= f.password_field :password, class: "form-control" %>
  </div> 
  <div class="form-group">
    <%= f.label "パスワード(確認)" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div> 
  <div class="form-group">
    <%= f.label "アイコン画像(任意項目)" %></br>
    <%= f.file_field :image %>
  </div>
  <div class="text-center">
    <%= f.submit "送信", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for(:html_title) { 'ユーザー情報編集' } %>
<div class="container user-container">
  <h2>ユーザー情報変更</h2>
  <div class="row">
    <div class="col-md-8 offset-md-2 col-sm-12" >
    <%= render "form" %>
    </div>  
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:html_title) { 'サインアップ' } %>
<div class="container user-container">
  <h2>サインアップ</h2>
  <div class="signup-form row">
    <div class="col-md-6 offset-md-3" >
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:html_title) { 'ユーザーページ' } %>

<div class="container user_show_container">
  <div class="row">
    <aside class="col-md-3">
      <%= image_tag @user.image.url, class:"review-icon", size:"100x100" %>
      <h3><%= @user.name %></h3>
      <%= link_to "プロフィール編集", edit_user_path(@user) %> | <%= link_to "退会する", user_path, method: :delete %>
    </aside>
    
    <div class="col-md-9">
      <h3>お気に入り</h3>
        <div class="row">
          <% @studios.each do |studio| %>
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card img-thumbnail h-100">
              <%= image_tag studio.image.url, class:"card-img-top", size:"300x250" %>
              <div class="card-body px-2 py-3">
                <h5 class="card-title"><%= link_to studio.name, studio_path(studio) %></h5>
                <small class="small-block"><i class="fas fa-map-marker-alt"></i> <cite title="<%= studio.address %>"><%= studio.address %> </small>
                <small class="small-block"><i class="fas fa-subway"></i><%= access_info(studio.accesses) %></small>
                <small class="small-block"><i class="far fa-clock"></i><%= studio.opening_hours %></small>
                <small class="small-block"><i class="fas fa-yen-sign"></i><%= studio.weekday_fee&.fee %></small>
                <div class="star-review" data-score="<%= rating(studio.reviews) %>"></div>
                <div class="score-review"><%= rating(studio.reviews) %></div>
                <p class="count-review"><i class="fa fa-comments"></i> <%= studio.reviews.count %></p>
                <p class="hash_tags"><i class="fas fa-tags"></i> 
                  <% studio.hash_tags.each do |hash_tag| %>
                    <%= link_to hash_tag.tag, studios_path(q: { hash_tags_id_in: [hash_tag.id] }) %>
                  <% end %>
                </p>
              </div><!-- /.card-body -->
            </div><!-- /.card -->
          </div><!-- /.col-sm-6.col-md-3 -->
        <% end %>
        
      </div><!-- /.row -->
        <%= will_paginate(@studios, class: "pagination justify-content-center", 
                              renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
  </div>
</div>