config/routes.rb
Rails.application.routes.draw do
  #get 'reviews/new'
  #get 'sessions/new'
  root 'static_pages#home'
  get '/login',     to: "sessions#new"
  post 'login',     to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :studios
  resources :users
  resources :favorites, only:[:create, :destroy]
  resources :reviews, only:[:new, :create, :destroy]
end

app/models/studio.rb
class Studio < ApplicationRecord
  #作ったユーザとのアソシエーション studio.created_user.name といった形で呼び出せる
  belongs_to :created_user, class_name: "User", optional: true
  #お気に入り
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user, dependent: :destroy
  #ハッシュタグ
  has_many :hash_tag_relationships, dependent: :destroy
  has_many :hash_tags, through: :hash_tag_relationships
  #レビュー
  has_many :review_relationships, dependent: :destroy
  has_many :reviews, through: :review_relationships, dependent: :destroy
  #アクセス
  has_many :accesses, dependent: :destroy
  #料金
  belongs_to :weekday_fee, class_name: "Fee", optional: true
  belongs_to :holiday_fee, class_name: "Fee", optional: true
  
  #カラムの名前をmount_uploaderに指定
  #THUMBNAIL_SIZE = [300, 250]
  mount_uploader :image, ImageUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :created_user_id, presence: true
  validates :place_id, uniqueness: true
=begin
  VALID_TELNO_REGEX = /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/
  VALID_URL_REGEX = /\A#{URI::regexp(%w(http https))}\z/
  validates :telno, format: { with: VALID_TELNO_REGEX }, allow_nil: true
=end

  
  def self.search_by_name(name)
    Studio.where('name LIKE ?',"%#{name}%")
  end
  
  def self.search_by_area(id)
    Studio.where('area_id = ?',"#{id.to_i}")
  end

  def regist_hash_tag(hash_tag_ids)
    hash_tag_ids.each do |hash_tag_id|
      hash_tag = HashTagRelationship.new(studio_id: self.id, hash_tag_id: hash_tag_id)
      hash_tag.save
    end
  end
  
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :log_in_user, only:[:create, :new, :edit, :update, :destroy]

  # get /studios
  def index
    @q = Studio.search(search_params)
    @q_studios = @q.result(distinct: true).includes(:hash_tags, :hash_tag_relationships, :accesses, :weekday_fee).paginate(page: params[:page], per_page: 9)
  end

  # post /studios
  def create
    #debugger
    @studio = Studio.new(studio_params)
    @studio.created_user_id = @current_user.id
    geocode(@studio)
    save_photo(@studio) if @studio.image.blank?
    #debugger
    if @studio.save
      create_access(@studio)
      @studio.regist_hash_tag(params[:studio][:hash_tags])
      flash[:success] = "スタジオの登録に成功しました！"
      redirect_to studio_path(@studio)
    else
      flash.now[:danger] = "スタジオの登録に失敗しました。"
      render 'new'
    end
  end
  
  # get /studios/new
  def new
    @studio = Studio.new
    @hash_tags = HashTag.all
  end
  
  # get /studios/:id/edit
  def edit
    @studio = Studio.find(params[:id])
    @hash_tags = @studio.hash_tags
  end
  
  # get /studios/:id
  def show
    @favorite = Favorite.new 
    @studio = Studio.find(params[:id])
    @hash_tags = @studio.hash_tags
    @reviews   = @studio.reviews.includes(:user).paginate(page: params[:page], per_page: 2)
  end

  # patch /studios/:id
  def update
    @studio = Studio.find(params[:id])
    @studio.assign_attributes(studio_params)
    geocode(@studio)
    save_photo(@studio)
    #住所再登録の場合はアクセス情報の再登録
    if @studio.address_changed?
      @studio.accesses.destroy_all
      create_access(@studio)
    end
    if @studio.save
      @studio.regist_hash_tag(params[:studio][:hash_tags])
      flash[:success] = "スタジオの編集に成功しました。"
      redirect_to studio_path(@studio)
    else
      flash.now[:danger] = "スタジオの編集に失敗しました。"
      render 'edit'
    end
  end
  
  # delete /studios/:id
  def destroy
    Studio.find(params[:id]).destroy
    flash[:success] = "スタジオの削除に成功しました。"
    redirect_to user_path(current_user)
  end
  
  private
    def search_params
      #params.require(:q).permit(:hash_tags_id_in => [], groupings: [:name_or_address_cont])
      params.require(:q).permit!

    end
  
    def studio_params
      params.require(:studio).permit(:name,
                                     :address,
                                     :image,
                                     :telno,
                                     :url,
                                     :latitude,
                                     :longitude,
                                     :opening_hours,
                                     :weekday_fee_id,
                                     :holiday_fee_id
                                     #{:hash_tag_ids => []}
                                     )
    end
    
    def geocode(studio)
      uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+studio.address.gsub(" ", "")+"&key=#{ENV['GOOGLEMAPS_IP_KEY']}")
      res = HTTP.get(uri).to_s
      response = JSON.parse(res)
      studio.place_id  = response["results"][0]["place_id"]
      studio.latitude  = response["results"][0]["geometry"]["location"]["lat"]
      studio.longitude = response["results"][0]["geometry"]["location"]["lng"]
    end
    
    def save_photo(studio)
      uri = URI.parse URI.encode "https://maps.googleapis.com/maps/api/place/details/json?placeid=#{studio.place_id}&key=#{ENV['GOOGLEMAPS_IP_KEY']}"
      res = HTTP.get(uri).to_s
      response = JSON.parse(res)
      result = response["result"]
      if result&.has_key?("photos")
        photo_reference = result['photos'][0]['photo_reference'] 
        url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&maxheight=400&photoreference=#{photo_reference}&key=#{ENV['GOOGLEMAPS_IP_KEY']}"
        studio.remote_image_url = url
      end
    end
    
    def create_access(studio)
      x = studio.longitude.to_f
      y = studio.latitude.to_f
      access_uri = URI.parse URI.encode "http://map.simpleapi.net/stationapi?x=#{x}&y=#{y}&output=json"
      access_res = HTTP.get(access_uri).to_s
      access_responses = JSON.parse(access_res)
      access_responses.each do |access_response|
        Access.create(name: access_response["name"],
                            line: access_response["line"],
                            distanceKm: access_response["distanceKm"],
                            traveltime: access_response["traveltime"],
                            studio_id: studio.id)
      end
    end
    
end

app/helpers/studios_helper.rb
module StudiosHelper
  def show_current_number(current_page,size)
    if size > 8
      first = 1
      last  = size
      last *= current_page
      first = last -8
      return "#{first} ~ #{last}"
    else
      return "1 ~ #{size}"
    end
  end
  
  def rating(reviews)
    rate = 0.0
    if reviews.any?
      reviews.each { |review| rate += review.rate.to_f }
      rate /= reviews.count
    end
    return rate.round(2)
  end
  
  def show_search_words(words)
    ary = []
    words.each { |word| ary.push word[:name_or_address_cont] }
    ary.join(" ")
  end
  
  def line_info(access)
    if access&.line.include?("ほか")
      return access&.line.slice(0..-3)
    else
      return access&.line
    end
  end
end

app/views/studios/_error_messages.html.erb
<% if @studio.errors.any? %>
  <div class="error_messages">
  <% @studio.errors.full_messages.each do |message| %>
    <ul>
      <li class="error-messages"><%= message %></li>
    </ul>
  <% end %>
  </div>
<% end %>

app/views/studios/_favorite.html.erb
<%= link_to favorites_path(:studio_id => @studio.id), method: :post, remote: true do %>
  <i class="far fa-bookmark"></i>
<% end %>

app/views/studios/_favorite_form.html.erb
<!-- log_in? でFavoriteForm表示の有無を決める-->
<div id="favorite_form">
  <% if Favorite.find_by(user_id: current_user.id, studio_id: @studio.id) %>
    <%= render "unfavorite" %>
  <% else %>
    <%= render "favorite" %>
  <% end %>
</div>

app/views/studios/_form.html.erb
<%= render "error_messages" %>
<%= form_for(@studio) do |f| %>
  <div class="form-group">
    <%= f.label "スタジオ名(必須項目)" %>
    <%= f.text_field :name, class: "form-control", placeholder: "例) スタサーチ" %>
  </div>
  <div class="form-group">
    <%= f.label "住所(必須項目)" %>
    <%= f.text_field :address, class: "form-control", placeholder: "例) 〇〇県〇〇市〇〇町1-1-1" %>
  </div>
  <div class="form-group">
    <%= f.label :電話番号 %>
    <%= f.text_field :telno, class: "form-control", placeholder: "例) 000-0000-0000" %>
  </div>
  <div class="form-group">
    <%= f.label "URL" %>
    <%= f.text_field :url, class: "form-control", placeholder: "例) https://sta-search.herokuapp.com/" %>
  </div>
  <div class="form-group">
    <%= f.label "営業時間" %>
    <%= f.text_field :opening_hours, class: "form-control", placeholder: "例)　[平日]24時間営業 [休日]9:00~22:00" %>
  </div>
  <div class="form-group">
    <%= f.label "平日料金/1h" %></br>
    <%= f.select :weekday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label "休日料金/1h" %></br>
    <%= f.select :holiday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label "スタジオの画像 (未選択の場合はGoogle Placesから自動取得します。)" %></br>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :ハッシュタグ %></br>
      <%= f.collection_check_boxes :hash_tags, HashTag.all, :id, :tag %>
  </div>
  <div class="text-center">
    <%= f.submit "送信", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/studios/_hash_tag.html.erb
<% @hash_tags.each do |hash_tag| %>
  <%= link_to hash_tag.tag, studios_path(q: { hash_tags_id_in: [hash_tag.id] }) %> 
<% end %>

app/views/studios/_limited_form.html.erb
<%= render "error_messages" %>
<%= form_for(@studio) do |f| %>
  <div class="form-group">
      <%= f.label "住所(必須項目)" %>
      <%= f.text_field :address, class: "form-control", placeholder: "例) 〇〇県〇〇市〇〇町1-1-1" %>
    </div>
    <div class="form-group">
      <%= f.label "電話番号(任意項目)" %>
      <%= f.text_field :telno, class: "form-control", placeholder: "例) 000-0000-0000" %>
    </div>
    <div class="form-group">
      <%= f.label "URL(任意項目)" %>
      <%= f.text_field :url, class: "form-control", placeholder: "例) https://sta-search.herokuapp.com/" %>
    </div>
    <div class="form-group">
      <%= f.label "営業時間(任意項目)" %>
      <%= f.text_field :opening_hours, class: "form-control", placeholder: "例)　[平日]24時間営業 [休日]9:00~22:00" %>
    </div>
    <div class="form-group">
      <%= f.label "平日料金/1h(任意項目)" %></br>
      <%= f.select :weekday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label "休日料金/1h(任意項目)" %></br>
      <%= f.select :holiday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label "スタジオの画像 (任意項目 未選択の場合はGoogle Placesから自動取得します。)" %></br>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label "ハッシュタグ(任意項目)" %></br>
        <%= f.collection_check_boxes :hash_tags, HashTag.all, :id, :tag %>
    </div>
    <div class="text-center">
      <%= f.submit "送信", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/studios/_more.html.erb
<%= will_paginate(@reviews, class: "pagination justify-content-center", 
                              renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/studios/_reviews.html.erb
<% @reviews.each do |review| %>
<div class="review row text-left">
  <div class="icon col-sm-2 offset-sm-1 col-4"><%= image_tag review.user.image.url, class:"review-icon", size:"50x50" %></div>
  <div class="balloon col-8 text-left">
    <div class="review_title"><%= review.title %></div>
    <div class="star-review" data-score="<%= review.rate %>"></div>
    <div class="review_content"><%= simple_format(review.review) %></div>
  </div>
</div>
<% end %>

app/views/studios/_search_form.html.erb
<%= search_form_for(@q, html: { class: 'form-holizontal' }, url:search_path) do |f| %>
  <div class="row">
    <div class="form-inline col-sm-10 ">
    <%= f.search_field :name_or_address_cont, class:"form-control", placeholder:"検索" %>
    <%= f.submit "検索", class:"btn btn-primary" %>
    </div>
  </div>
  <div class="form-check">
    <label>
      <%= f.collection_check_boxes :hash_tags_id_in, @hash_tags, :id, :tag, class: "white" %>
    </label>
  </div>
<% end %>

app/views/studios/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(studio_id: @studio.id), :studio_id => @studio.id), method: :delete, remote: true do %>
  <i class="fas fa-bookmark"></i>
<% end %>

app/views/studios/edit.html.erb
<% content_for(:html_title) { 'スタジオ編集' } %>

<div class="container studio-container">
  <h2>編集フォーム</h2>
  <div class="row">
  <div class="col-md-8 offset-md-2 col-sm-12">
  <% if current_user.id == @studio.created_user.id %>
    <%= render "form" %>
  <% else %>
    <%= render "limited_form" %>
  <% end %>
  </div>
  </div>
</div>

app/views/studios/index.html.erb
<% content_for(:html_title) { '検索結果' } %>

<div class="container index-container">

  <div class="search_query">
  <h4>検索条件</h4>
  <% unless params[:q][:groupings].nil? or params[:q][:groupings].empty? %>
    <% words = params[:q][:groupings] %>
    検索ワード:<%= show_search_words(words) %>
  <% end %>
  <br>
  <% unless params[:q][:hash_tags_id_in].nil? or params[:q][:hash_tags_id_in]&.reject(&:blank?).empty? %>
    ハッシュタグ:<%= params[:q][:hash_tags_id_in].reject(&:blank?).map{|hash_tag_id| HashTag.find(hash_tag_id).tag}.join(', ') %>
  <% end %>
  </div>
  
  <div class="search-number-container">
    <p class="search-number"><%= show_current_number(@q_studios.current_page,@q_studios.size) %>件を表示 ／ 全<%= @q_studios.total_entries %>件</p>
  </div>

  <div class="row">
    <% @q_studios.each do |studio| %>
    <div class="col-sm-12 col-md-6 col-lg-4">
      <div class="card img-thumbnail h-100">
        <%= image_tag studio.image.url, class:"card-img-top", size:"300x250" %>
        <div class="card-body px-2 py-3">
          <h5 class="card-title"><%= link_to studio.name, studio_path(studio) %></h5>
          <small class="small-block"><i class="fas fa-map-marker-alt"></i> <cite title="<%= studio.address %>"><%= studio.address %> </small>
          <small class="small-block"><i class="fas fa-subway"></i><%= access_info(studio.accesses) %></small>
          <small class="small-block"><i class="far fa-clock"></i><%= studio.opening_hours %></small>
          <small class="small-block"><i class="fas fa-yen-sign"></i><%= studio.weekday_fee&.fee %></small>
          <div class="star-review" data-score="<%= rating(studio.reviews) %>"></div>
          <div class="score-review"><%= rating(studio.reviews) %></div>
          <p class="count-review"><i class="fa fa-comments"></i> <%= studio.reviews.count %></p>
          <p class="hash_tags"><i class="fas fa-tags"></i> 
            <% studio.hash_tags.each do |hash_tag| %>
              <%= link_to hash_tag.tag, studios_path(q: { hash_tags_id_in: [hash_tag.id] }) %> <!-- 配列じゃないと検索できないため、idを[]で括っている -->
            <% end %>
          </p>
        </div><!-- /.card-body -->
      </div><!-- /.card -->
    </div><!-- /.col-sm-6.col-md-3 -->
  <% end %>
  </div><!-- /.row -->

  <%= will_paginate(@q_studios, class: "pagination justify-content-center", 
                              renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

<script>
window.onunload = function(){};

$('.star-review').raty({
  path: '/assets/',
  readOnly: true,
  score: function() {
          return $(this).attr('data-score');
        }
});
window.onpageshow = function(event) {
	if (event.persisted) {
		 window.location.reload();
	}
};

</script>

app/views/studios/new.html.erb
<% content_for(:html_title) { 'スタジオ登録' } %>
<div class="container studio-container">
  <h2>新規スタジオ登録</h2>
  <%= render "error_messages" %>
  <div class="row">
    <div class="col-md-8 offset-md-2 col-sm-12" >
  <%= form_for(@studio) do |f| %>
    <div class="form-group">
      <%= f.label "スタジオ名(必須項目)" %>
      <%= f.text_field :name, class: "form-control", placeholder: "例) スタサーチ" %>
    </div>
    <div class="form-group">
      <%= f.label "住所(必須項目)" %>
      <%= f.text_field :address, class: "form-control", placeholder: "例) 〇〇県〇〇市〇〇町1-1-1" %>
    </div>
    <div class="form-group">
      <%= f.label "電話番号(任意項目)" %>
      <%= f.text_field :telno, class: "form-control", placeholder: "例) 000-0000-0000" %>
    </div>
    <div class="form-group">
      <%= f.label "URL(任意項目)" %>
      <%= f.text_field :url, class: "form-control", placeholder: "例) https://sta-search.herokuapp.com/" %>
    </div>
    <div class="form-group">
      <%= f.label "営業時間(任意項目)" %>
      <%= f.text_field :opening_hours, class: "form-control", placeholder: "例)　[平日]24時間営業 [休日]9:00~22:00" %>
    </div>
    <div class="form-group">
      <%= f.label "平日料金/1h(任意項目)" %></br>
      <%= f.select :weekday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label "休日料金/1h(任意項目)" %></br>
      <%= f.select :holiday_fee_id, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label "スタジオの画像 (任意項目 未選択の場合はGoogle Placesから自動取得します。)" %></br>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label "ハッシュタグ(任意項目)" %></br>
        <%= f.collection_check_boxes :hash_tags, HashTag.all, :id, :tag %>
    </div>
    <div class="text-center">
      <%= f.submit "送信", class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>
  </div>
</div>

<script>
  var obj = document.getElementById("range");
  function showValue() {
    document.getElementById("value").textContent = option.value;
    
  }
  obj.addEventListener("change", showValue, false);
</script>

app/views/studios/show.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v3.2"></script>

<% set_meta_tags description: "#{@studio.accesses}の音楽スタジオ #{@studio.name}の詳細情報ページ" %>
<% set_meta_tags og: {title: "#{@studio.name} | スタサーチ", image: "#{@studio.image_url}"} %>

<% content_for(:html_title) { @studio.name } %>
<div class="container show-studio-container">
  <div class="row">
    <div class="col-xl-8 col-12">
      <div class="card">
        <div class="card-header text-left">
          <h2 class="show-studio-header"><%= @studio.name %> <%= render "favorite_form" if logged_in? %></h2>
          <div class="rating"><div id="star-head" data-score="<%= rating(@reviews) %>"></div> <p class="rate-score"><%= rating(@reviews) %></p></div>
        </div>
        <div>
          <%= image_tag @studio.image.url, class:"card-img img-responsive" %>
        </div>
        <div class="card-body">
          <p><i class="fas fa-tags"></i> <%= render "hash_tag" %></p>
          
          <p class="card-text updated_at"><%= link_to "編集", edit_studio_path %> | 最終更新日：<%= @studio.updated_at %></p>
          
          <div class="share_btn_container">
            <div class="twitter share_btn">
            　<a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @studio.name %> <%= @studio_url %> #スタサーチ" data-lang="ja"></a>
            </div>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            
            <div class="fb-share-button share_btn pb-10" data-href="<%= @studio_url %>" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a></div>
  
            <div class="line-it-button share_btn" data-lang="ja" data-type="share-a" data-url="<%= @studio.url %>" style="display: none;"></div>
            <script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
          </div>
        </div>
      </div><!-- card -->
    </div><!-- col -->
    
    <div class="col-xl-4 col-12">
      <div class="card">
        <div class="card-header">
          <h5>店舗情報</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="fas fa-map-marker-alt fa-fw"></i> 住所
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= @studio.address %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="fas fa-subway fa-fw"></i> 最寄駅
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= access_info(@studio.accesses) %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="fas fa-phone fa-fw"></i> 電話番号
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= @studio.telno %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="fas fa-globe-europe fa-fw"></i> URL
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <a href = "<%= @studio.url %>"><%= @studio.url %></a>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="far fa-clock fa-fw"></i> 営業時間
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= @studio.opening_hours %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <i class="fas fa-yen-sign fa-fw"></i> 平日料金
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= @studio.weekday_fee&.fee %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 col-5 text-left pl-2">
              <span class="holiday"></span> 休日料金
            </div>
            <div class="col-sm-8 col-7 text-left px-0">
              <%= @studio.holiday_fee&.fee %>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <h5>マップ</h5>
        </div>
        <div class="card-body">
          <div id="map" style='width: 100%; height: 28vh;'></div>
        </div>
        <p class="access">
          <%= line_info(@studio.accesses&.first) %><%= @studio.accesses&.first.name %>から<%= @studio.accesses&.first.distanceKm %>
        </p>
        <p class="access">
          <%= @studio.accesses&.first.traveltime %>
        </p>
        <p class="access">
          <%= link_to "GoogleMapで開く", "https://www.google.com/maps/search/?api=1&query=#{@studio.latitude},#{@studio.longitude}&query_place_id=#{@studio.place_id}" , target: "_blank" %>
        </p>
      </div>
    </div>
  </div><!-- row -->
  
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          レビュー　全<%= @reviews.count %>件
          <%= render "more" %>
        </div>
        <div id="reviews">
          <%= render "reviews" %>
        </div>
        
        <%= link_to "レビューを投稿", new_review_path(studio_id: @studio.id) %>
      </div>
    </div>
  </div>
  <% if logged_in? and !@studio.created_user.id.nil? %>
    <%= link_to "削除する", studio_path(@studio), method: :delete if current_user.id == @studio.created_user.id %>
  <% end %>
</div>




<script type="text/javascript">
  function initMap() {

    var test = {lat: <%= @studio.latitude %>, lng: <%= @studio.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: test
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @studio.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
  
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLEMAPS_HTTP_KEY'] %>&callback=initMap">
</script>

<script>
$('#star-head').raty({
  starOn: '<%= asset_path('star-on-big.png') %>',
  starOff: '<%= asset_path('star-off-big.png') %>',
  starHalf: '<%= asset_path('star-half-big.png') %>',

  readOnly: true,
  half: true,
  score: function() {
          return $(this).attr('data-score');
        }
});
$('.star-review').raty({
  path: '/assets/',
  readOnly: true,
  score: function() {
          return $(this).attr('data-score');
        }
});
</script>