config/routes.rb
Rails.application.routes.draw do
  #get 'reviews/new'
  #get 'sessions/new'
  root 'static_pages#home'
  get '/login',     to: "sessions#new"
  post 'login',     to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :studios
  resources :users
  resources :favorites, only:[:create, :destroy]
  resources :reviews, only:[:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) + " | スタサーチ" : "スタサーチ - 口コミとランキングで選べる音楽スタジオ探し" %></title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path %>"><i class="fas fa-guitar"></i> スタサーチ</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item active">
                <%= link_to "スタジオを投稿する", new_studio_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ユーザートップ", user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to "新規登録", new_user_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", login_path, class: "nav-link" %>
              </li>
            <% end %>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"><i class="fas fa-search"></i></button>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container">
      <%= render 'shared/flash' %>
      <!-- モーダルウィンドウの中身 -->
      <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">スタジオ検索</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
              <%= search_form_for(@q, html: { class: '.d-none' }, url:studios_path) do |f| %>
                <div class="form-row">
                  <div class="col-lg-4 col-4 px-0 ">
                    <%= f.search_field :accesses_name_or_accesses_line_cont, class:"form-control", placeholder:"路線名・駅名" %>
                  </div>
                  <div class="col-lg-6 col-6 px-0 ">
                    <%= f.search_field :name_or_address_cont, class:"form-control", placeholder:"スタジオ名" %>
                  </div>
                  <div class="col-2 px-0 ">
                  	<%= f.submit "検索", class:"btn btn-primary" %>
                  </div>
                </div>
                <a href="#" data-toggle="collapse" data-target="#collapseModal" aria-expanded="false" aria-controls="collapseModal">▼ 詳細条件の表示</a>
                <div class="collapse" id="collapseModal">
                  <div class="form-row">
                    <div class="form-gorup col-6">
                      <%= f.label "平日価格帯" %>
                      <%= f.select :weekday_fee_id_eq, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
                    </div>
                    <div class="form-gorup col-6">
                      <%= f.label "休日価格帯" %>
                      <%= f.select :holiday_fee_id_eq, options_from_collection_for_select(Fee.all, :id, :fee), {include_blank:true}, {class: "form-control"} %>
                    </div>
                    <div class="form-check col-12">
                      <%= f.label "特徴" %></br>
                    　<%= f.collection_check_boxes :hash_tags_id_in, @q_hash_tags, :id, :tag %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
      <%= yield %>  
    <footer class="footer">
      <div class="container text-center">
        <p class="text-muted">©2019 StaSearch All Rights Reserved.</p>
      </div>
    </footer>

  </body>
  
<script type="text/javascript">
  $(document).ready(function() {
    $('.multiselect').multiselect({
      buttonText: function(options, select) {
        if (options.length === 0) {
          return '特徴';
        }else{
          return `${options.length} 選択`;
        }
      }
    });
  });
</script>

<input type="hidden" id="refresh" value="no">
<script>
$(document).ready(function() {
    var $input = $('#refresh');
    $input.val() == 'yes' ? location.reload(true) : $input.val('yes');
});
</script>
</html>